import Head from "next/head";
import Link from "next/link";
import styles from "@styles/Layout.module.css";
import Header from "@components/Header";
import Footer from "@components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Link href="/pokemon">
          <a>View all Pokemon</a>
        </Link>

        <p className={styles.explainer}>
          This is a static route. Find the file at <code>/pages/index.js</code>
        </p>
      </main>

      <Footer />
    </div>
  );
}
